commit for pr
krlktv/shopno pull request #1
Opened 2021-07-04 11:08 UTC by krlktv

Fix hover-animation freezes.
Fix the favicon error in the console.
Fix the href of the header logo link (shopno).
Fix (cancele) form submission and add form cleanup on button click.
Fix (change) grid to flexbox in blocks works and team.

2021-07-06 15:43 UTC, maximsan requested changes
Hello! I left several comments. I found out what we can improve. Let me know if something unclear. You've added gulp and that's cool! Thanks! Good work!

2021-07-06 15:43 UTC, maximsan commented on src/index.html
> +			<div class="about__wrapper">
Semantically It's not correct to use this name here, because `about__wrapper` according to its name should be wrapper around `about` section. Looks like you broke it a little :)

2021-07-06 15:43 UTC, maximsan commented on src/index.html
> +	<div class="popup hide">
If we follow `BEM` we should name it like `popup popup--hide` or `popup popup_hide`, because `popup--hide` or ` popup_hide` in this case is modificator

2021-07-06 15:43 UTC, maximsan commented on src/index.html
> +			<div class="works__wrapper">
The same is here with name `works__wrapper`

2021-07-06 15:43 UTC, maximsan commented on src/index.html
> +			<div class="team__wrapper">
The same is here with name `team__wrapper`

2021-07-06 15:43 UTC, maximsan commented on src/index.html
> +				<div class="team__member" style="background-image: url(img/team/person1.jpg);">
Why do you use inline styles ? Use styles from css file

2021-07-06 15:43 UTC, maximsan commented on src/index.html
> +				<div class="team__member" style="background-image: url(img/team/person2.jpg);">
The same is here. Why do you use inline styles ? Use styles from css file

2021-07-06 15:43 UTC, maximsan commented on src/index.html
> +						Address line 1<br>
let's avoid using of <br/> tag, we have more neat tags for this

2021-07-06 15:43 UTC, maximsan commented on src/index.html
> +					<input type="text" name="email" id="email" class="form__item" placeholder="E-mail*" required>
could you add attrbiute wtih email **regexp** ?

2021-07-06 15:43 UTC, maximsan commented on dist/js/script.js
> +
You should minify and uglify it too :)

2021-07-06 15:43 UTC, maximsan commented on src/sass/blocks/_about.scss
> +		padding-top: 130px;
you can use variable for this value

2021-07-06 15:43 UTC, maximsan commented on src/sass/blocks/_contacts.scss
> +			color: rgba(255, 255, 255, .6);
you can use variables for the colors

2021-07-06 15:43 UTC, maximsan commented on src/sass/blocks/_contacts.scss
> +				color: #fff;
you can use variables for the colors

2021-07-06 15:43 UTC, maximsan commented on src/sass/blocks/_team.scss
> +			font-family: 'Raleway', sans-serif;
specify this value on the root level, in main file to avoid repetition in many places, I guess you have the same font-family everywhere. you should do the same for all common styles. it's also a good if you add file with reset/sanitize styles to remove browser default styles

2021-07-06 15:43 UTC, maximsan commented on src/sass/style.scss
> +	padding: 0;
don't forget about box-sizing, font-family, font-size, a, p and etc. I guess you can move part of you common styles here

2021-07-12 09:31 UTC, krlktv commented on src/index.html
> +			<div class="about__wrapper">
Thanks. I fixed it.
```suggestion
			<div class="about__content">
```

2021-07-12 09:33 UTC, krlktv commented on src/index.html
> +			<div class="works__wrapper">
Thanks. I fixed it.
```suggestion
			<div class="works__content">
```

2021-07-12 09:33 UTC, krlktv commented on src/index.html
> +			<div class="team__wrapper">
Thanks. I fixed it.
```suggestion
			<div class="team__content">
```

2021-07-12 09:36 UTC, krlktv commented on src/index.html
> +	<div class="popup hide">
Thanks. I fixed it.
```suggestion
	<div class="popup popup_hide">
```

2021-07-12 10:46 UTC, krlktv commented on src/index.html
> +				<div class="team__member" style="background-image: url(img/team/person1.jpg);">
Thanks. I fixed it.
```suggestion
				<div class="team__member team__member_img1">
```

2021-07-12 10:46 UTC, krlktv commented on src/index.html
> +				<div class="team__member" style="background-image: url(img/team/person2.jpg);">
Thanks. I fixed it.
```suggestion
				<div class="team__member team__member_img2">
```

2021-07-12 10:53 UTC, krlktv commented on src/index.html
> +						Address line 1<br>
```suggestion
						<div>Address line 1</div>
```

2021-07-12 11:10 UTC, krlktv commented on src/sass/blocks/_team.scss
> +			font-family: 'Raleway', sans-serif;
Three different font families are used, the main one is not defined.
Browser default styles have been already removed by import bootstrap-reboot.min at style.scss.
`@import 'libs/bootstrap-reboot.min';`

2021-07-12 11:27 UTC, krlktv commented on src/sass/style.scss
> +	padding: 0;
Thank you.
```suggestion
	padding: 0;
	box-sizing: border-box;
```

2021-07-12 11:44 UTC, krlktv commented on src/sass/blocks/_about.scss
> +		padding-top: 130px;
Thanks. I added mixins.
```suggestion
		@include flex_space_around;
```

2021-07-12 12:08 UTC, krlktv commented on src/sass/blocks/_contacts.scss
> +			color: rgba(255, 255, 255, .6);
Thanks. I fixed it.
```suggestion
			color: $text-gray-color;
```

2021-07-12 12:09 UTC, krlktv commented on src/sass/blocks/_contacts.scss
> +				color: #fff;
Thanks. I fixed it.
```suggestion
				color: $text-light-color;
```

2021-07-12 12:17 UTC, krlktv commented on src/index.html
> +					<input type="text" name="email" id="email" class="form__item" placeholder="E-mail*" required>
```suggestion
					<input type="email" name="email" id="email" class="form__item" placeholder="E-mail*" required pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$">
```

2021-07-12 12:29 UTC, krlktv commented on dist/js/script.js
> +
Thanks. I fixed it.
```suggestion
"use strict";const popupTrigger=document.querySelectorAll(".works__img"),popup=document.querySelector(".popup");function closePopup(){popup.classList.add("popup_hide"),popup.classList.remove("popup_show"),document.body.style.overflow=""}function openPopup(){popup.classList.add("popup_show"),popup.classList.remove("popup_hide"),document.body.style.overflow="hidden"}popupTrigger.forEach((p,e)=>{p.addEventListener("click",p=>{document.querySelector(".popup__img").src=p.target.src}),p.addEventListener("click",openPopup)}),popup.addEventListener("click",p=>{p.target===popup&&closePopup()}),document.addEventListener("keydown",p=>{"Escape"===p.code&&popup.classList.contains("popup_show")&&closePopup()});const form=document.querySelector("#form");form.addEventListener("submit",function(p){p.preventDefault(),form.reset()});
```

2021-07-13 16:07 UTC, maximsan approved these changes
Hello. Looks better!

2021-07-13 16:07 UTC, maximsan commented on src/sass/blocks/_media.scss
> +				width: 300px;
try to use max-width/max-height everywhere and em/rem/%, because we want our page to be responsive

2021-07-13 16:57 UTC, krlktv commented on src/sass/blocks/_media.scss
> +				width: 300px;
Got it. Thank you for the advice!

2021-07-13 18:26 UTC, Dev1LtJ commented
I trust to @maximsan's approve.

2021-07-13 18:28 UTC, Dev1LtJ approved these changes

2021-07-13 19:24 UTC, merged